version: '2'
services:
    rffaixas-app:
        image: rffaixas
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rffaixas-postgresql:5432/rffaixas
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=internal
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=internal
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    rffaixas-postgresql:
        extends:
            file: postgresql.yml
            service: rffaixas-postgresql
